# Generated by Django 4.1.7 on 2023-03-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('car', models.CharField(choices=[('Porsche 911 Carrera', 'Porsche 911 Carrera'), ('Porsche 911 Turbo', 'Porsche 911 Turbo'), ('Porsche Cayman', 'Porsche Cayman'), ('Porsche Cayman GTS 4.0 ', 'Porsche Cayman GTS 4.0 '), ('Porsche Macan', 'Porsche Macan'), ('Porsche Panamera', 'Porsche Panamera'), ('Porsche Cayenne', 'Porsche Cayenne'), ('Porsche Taycan', 'Porsche Taycan'), ('Porsche Cayman', 'Porsche Cayman')], max_length=60)),
                ('mileage', models.IntegerField()),
                ('phonenum', models.IntegerField()),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
    ]
