# Generated by Django 4.1.7 on 2023-03-13 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='register',
            name='mileage',
        ),
    ]
